/*The function ouch reacts to the signal that is passed in the parameter sig . This function will be called
when a signal occurs. It prints a message and then resets the signal handling for SIGINT (by default,
generated by typing Ctrl+C) back to the default behavior.
*/
#include<stdio.h>
#include<stdlib.h>
#include<unistd.h>
#include <signal.h>

void ouch(int sig)   // this is signal handler
 {
   printf("OUCH ! i got signal:%d\n",sig);
   (void) signal(SIGINT,SIG_DFL);   // SIGINT-CTRL+C,SIG_DFL-Restore default behavior.
 }

int main()
{
   (void) signal(SIGINT,ouch);  // initialisation of signal 
    while(1)
     {
       printf("hello world\n");
       sleep(1);
     }
 }
 
